#port
server:
  port: 80
  tomcat:
    max-threads: 256
    min-spare-threads: 5
#spring resource
spring:
  datasource:
    url: jdbc:mysql:///jtsys?serverTimezone=GMT%2B8&characterEncoding=utf8
    username: root
    password: root
  thymeleaf:
    prefix: classpath:/templates/pages/
    cache: false
  aop:
    proxy-target-class: false
  task:
    execution:
      pool:
        core-size: 5
        max-size: 128
        queue-capacity: 128
        keep-alive: 60000
      thread-name-prefix: db-service-task-

mybatis:
  mapper-locations:
  - classpath:/mapper/*/*.xml
  
shiro:
  loginUrl: /doLoginUI
  web:
    enabled: true
  sessionManager:
    sessionIdCookieEnabled: true
    sessionIdUrlRewritingEnabled: false
  rememberMeManager: 
    cookie: 
      name: rememberMe 
      maxAge: 3600
   
#log
logging:
  level:
   com.cy: debug
    